FROM rocker/shiny-verse
LABEL MAINTAINER="clintko"

RUN apt-get update
RUN apt-get update -qq && install2.r --error \
    --deps TRUE \
    vroom \
    flexdashboard \
    && rm -rf /tmp/downloaded_packages